library(jagsUI)
library(coda)
library(IPMbook)

y <- as.matrix(bin.histories[,-1])  # Remove AnimalID column
y <- unname(y)
n_ind <- nrow(y)
n_occasions <- ncol(y)

# Get first capture occasion for each individual
get_first <- function(x) min(which(x != 0))
first <- apply(y, 1, get_first)

# Bundle data for JAGS
jags.data <- list(
  y = y,
  nind = n_ind,
  nyears = n_occasions,
  f = first
)
str(jags.data)

# Save/load data bundle for annual model
#saveRDS(jags.data, file = "jags_data_ann.RDS")
jags.data <- readRDS("jags_data_ann.RDS")

# Annual survival model
cat(file = "cjs_model_annual.txt", "
model {
  # Priors
  phi.const ~ dunif(0, 1)        # Vague prior for constant survival probability
  p.const ~ dunif(0, 1)          # Vague prior for constant detection probability
  
  for (i in 1:nind){                 # Loop over individuals
    for (t in f[i]:(nyears-1)){      # Loop over intervals/occasions
    phi[i,t] <- phi.const             # Model pattern in phi...
    p[i,t] <- p.const                 # ... and p
    
    }
  }
  
  # Likelihood
  for (i in 1:nind){
    # Define latent state at first capture
    z[i,f[i]] <- 1
    for (t in (f[i]+1):nyears){ 
      # State process: does animal survive from t-1 to t?
      z[i,t] ~ dbern(z[i,t-1] * phi[i,t-1])
      
      # Observation process: is animal detected at t?
      y[i,t] ~ dbern(z[i,t] * p[i,t-1])
    }
  }
}
")

inits <- function(){list(z=zInit(jags.data.annual$y))}

params <- c("phi.const", "p.const")

# Run time: a few minutes
out_annual <- jags(jags.data, model.file = "cjs_model_annual.txt",
                inits = inits, parameters.to.save = params,
                n.chains = 3, n.iter = 5000, n.adapt = 1000, n.burnin = 1000,
                parallel = TRUE)
print(out_annual)

# JAGS output for model 'cjs_model_annual.txt', generated by jagsUI.
# Estimates based on 3 chains of 5000 iterations,
# adaptation = 1000 iterations (sufficient),
# burn-in = 1000 iterations and thin rate = 1,
# yielding 12000 total samples from the joint posterior. 
# MCMC ran in parallel for 0.689 minutes at time 2025-10-06 16:26:17.461736.
# 
# mean     sd     2.5%      50%    97.5% overlap0 f Rhat n.eff
# phi.const    0.830  0.008    0.815    0.830    0.845    FALSE 1    1 12000
# p.const      0.780  0.010    0.760    0.780    0.800    FALSE 1    1 12000
# deviance  2316.053 43.702 2232.496 2315.444 2404.898    FALSE 1    1  7476
# 
# Successful convergence based on Rhat values (all < 1.1). 
# Rhat is the potential scale reduction factor (at convergence, Rhat=1). 
# For each parameter, n.eff is a crude measure of effective sample size. 
# 
# overlap0 checks if 0 falls in the parameter's 95% credible interval.
# f is the proportion of the posterior with the same sign as the mean;
# i.e., our confidence that the parameter is positive or negative.
# 
# DIC info: (pD = var(deviance)/2) 
# pD = 954.9 and DIC = 3270.906 
# DIC is an estimate of expected predictive error (lower is better).

traceplot(out_annual)


# Monthly survival --------------------------------------------------------

y.monthly <- as.matrix(bin.histories.monthly[,-1])  # Remove AnimalID column
y.monthly <- unname(y.monthly)
n_ind.monthly <- nrow(y.monthly)
n_occasions.monthly <- ncol(y.monthly)

# Get first capture occasion for each individual
get_first <- function(x) min(which(x != 0))
first.monthly <- apply(y.monthly, 1, get_first)

# Bundle data for JAGS
jags.data.monthly <- list(
  y = y.monthly,
  nind = n_ind.monthly,
  nmonths = n_occasions.monthly,
  f = first.monthly
)
str(jags.data.monthly)

# Save/load data bundle for monthly model
#saveRDS(jags.data.monthly, file = "jags_data_monthly.RDS")
#jags.data.monthly <- readRDS("jags_data_monthly.RDS")

# Monthly survival model
cat(file = "cjs_model_monthly.txt", "
model {
  # Priors
  phi.month ~ dunif(0, 1)        # Vague prior for constant survival probability
  p.month ~ dunif(0, 1)          # Vague prior for constant detection probability
  
  for (i in 1:nind){                 # Loop over individuals
    for (t in f[i]:(nmonths-1)){      # Loop over intervals/occasions
    phi[i,t] <- phi.month             # Model pattern in phi...
    p[i,t] <- p.month                 # ... and p
    
    }
  }
  
  # Likelihood
  for (i in 1:nind){
    # Define latent state at first capture
    z[i,f[i]] <- 1
    for (t in (f[i]+1):nmonths){ 
      # State process: does animal survive from t-1 to t?
      z[i,t] ~ dbern(z[i,t-1] * phi[i,t-1])
      
      # Observation process: is animal detected at t?
      y[i,t] ~ dbern(z[i,t] * p[i,t-1])
    }
  }
  # Derived parameter: Annual survival from monthly
  phi.annual <- phi.month^12
}
")

inits <- function(){list(z=zInit(jags.data.monthly$y))}

params <- c("phi.month", "p.month", "phi.annual")

# Run time: a while
out_monthly <- jags(jags.data.monthly, model.file = "cjs_model_monthly.txt",
                inits = inits, parameters.to.save = params,
                n.chains = 3, n.iter = 20000, n.adapt = 5000, n.burnin = 5000, n.thin = 5,
                parallel = TRUE)
print(out_monthly)

# JAGS output for model 'cjs_model_monthly.txt', generated by jagsUI.
# Estimates based on 3 chains of 20000 iterations,
# adaptation = 5000 iterations (sufficient),
# burn-in = 5000 iterations and thin rate = 5,
# yielding 9000 total samples from the joint posterior. 
# MCMC ran in parallel for 102.982 minutes at time 2025-10-06 17:06:44.564473.
# 
# mean     sd      2.5%       50%     97.5% overlap0 f  Rhat n.eff
# phi.month      0.982  0.001     0.980     0.982     0.983    FALSE 1 1.000  3478
# p.month        0.259  0.003     0.253     0.259     0.264    FALSE 1 1.001  2404
# phi.annual     0.801  0.008     0.784     0.801     0.816    FALSE 1 1.000  3474
# deviance   29763.106 46.984 29672.560 29763.361 29856.490    FALSE 1 1.009   223
# 
# Successful convergence based on Rhat values (all < 1.1). 
# Rhat is the potential scale reduction factor (at convergence, Rhat=1). 
# For each parameter, n.eff is a crude measure of effective sample size. 
# 
# overlap0 checks if 0 falls in the parameter's 95% credible interval.
# f is the proportion of the posterior with the same sign as the mean;
# i.e., our confidence that the parameter is positive or negative.
# 
# DIC info: (pD = var(deviance)/2) 
# pD = 1094.1 and DIC = 30857.18 
# DIC is an estimate of expected predictive error (lower is better).

traceplot(out_monthly)
