# =============================================================================
# Shared paths and project-root guard
# =============================================================================
# Sourced at the top of every numbered script.  All other paths in the project
# are written relative to the project root, so scripts must be run with the
# root as the working directory -- opening luangwa-lion-ipm.Rproj does that.
#
# Only the raw inputs live here, because they are the files that are NOT in
# the repository (see .gitignore) and so differ between machines.

if (!dir.exists("R") || !dir.exists("data-raw")) {
  stop(
    "Working directory is not the project root.\n",
    "Open luangwa-lion-ipm.Rproj, or setwd() to the repository root, then re-run.\n",
    "Currently in: ",
    getwd()
  )
}

# --- raw inputs (not tracked by git) ----------------------------------------

# Access database of sightings
ACCESS_DB <- "data-raw/Luangwa Database - 2024Nov22 - MDF.accdb"

# Capture histories, lion IDs and litters from Mweetwa et al.'s PLOS ONE paper
FIRST_PAPER_DIR <- "data-raw/first-luangwa-paper"

# World Database on Protected Areas, Zambia extract, used for the park overlay.
# Download from https://www.protectedplanet.net (Zambia, WDPA + OECM, polygons).
WDPA_GDB <- "data-raw/wdpa/WDPA_WDOECM_Aug2026_Public_ZMB.gdb"
WDPA_LAYER <- "WDPA_WDOECM_poly_Aug2026_ZMB"

# --- derived outputs (regenerated by the scripts) ---------------------------
dir.create("data", showWarnings = FALSE)
dir.create("output", showWarnings = FALSE)

missing_inputs <- c(ACCESS_DB, FIRST_PAPER_DIR)[
  !file.exists(c(ACCESS_DB, FIRST_PAPER_DIR))
]
if (length(missing_inputs) > 0) {
  warning(
    "Missing raw inputs (see README):\n  ",
    paste(missing_inputs, collapse = "\n  ")
  )
}
